import { auth } from "@/config/firebase";
import { compressImageForUpload } from "@/utils/image";

/**
 * Uploads go to Cloudflare R2 via a presigned URL issued by our upload Worker
 * (see /worker). The app only knows the Worker's URL and the public base URL
 * of the bucket — never any R2 credentials.
 *
 * Object keys are generated by the Worker (the client just says what kind of
 * file it is and which property/maintenance request/user it belongs to):
 *   properties/{propertyId}/photos/{fileName}
 *   maintenance/{maintenanceId}/photos/{fileName}
 *   maintenance/{maintenanceId}/videos/{fileName}
 *   users/{userId}/profile/{fileName}
 */

type UploadKind = "property-photo" | "maintenance-photo" | "maintenance-video" | "profile-photo";

/**
 * Thrown for any failure in the R2 upload path (config, auth token, signing
 * request, or the upload itself). Its `message` is safe to show to users, and
 * screens can use `instanceof R2UploadError` to avoid reporting it as a
 * Firestore error.
 */
export class R2UploadError extends Error {
  constructor(message: string, cause?: unknown) {
    super(message);
    this.name = "R2UploadError";
    this.cause = cause;
  }
}

// Images are always re-encoded as JPEG by compressImageForUpload; videos keep
// whatever type the picker/OS reports (falling back to mp4).
const asJpeg = () => "image/jpeg";
const videoType = (blobType: string) => blobType || "video/mp4";

const UPLOAD_ENDPOINT = process.env.EXPO_PUBLIC_R2_UPLOAD_ENDPOINT;
const PUBLIC_URL = process.env.EXPO_PUBLIC_R2_PUBLIC_URL;

interface SignResponse {
  uploadUrl: string;
  key: string;
  headers?: Record<string, string>;
}

async function uploadUriTo(
  kind: UploadKind,
  ownerId: string,
  index: number,
  uri: string,
  contentTypeFor: (blobType: string) => string
): Promise<string> {
  if (!UPLOAD_ENDPOINT || !PUBLIC_URL) {
    throw new R2UploadError(
      "Photo upload isn't configured yet. Please contact support."
    );
  }

  const user = auth.currentUser;
  if (!user) throw new R2UploadError("You need to be signed in to upload files.");

  let idToken: string;
  try {
    idToken = await user.getIdToken();
  } catch (e) {
    throw new R2UploadError("Couldn't verify your session. Please sign in again.", e);
  }

  let blob: Blob;
  try {
    const response = await fetch(uri);
    blob = await response.blob();
  } catch (e) {
    throw new R2UploadError("Couldn't read the selected file.", e);
  }
  const contentType = contentTypeFor(blob.type);

  // 1. Ask our Worker for a short-lived presigned upload URL.
  let signed: SignResponse;
  try {
    const signRes = await fetch(`${UPLOAD_ENDPOINT.replace(/\/+$/, "")}/v1/uploads/sign`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${idToken}` },
      body: JSON.stringify({ kind, ownerId, index, contentType, size: blob.size }),
    });
    if (!signRes.ok) {
      const detail = await signRes.json().then((b) => b?.error as string | undefined, () => undefined);
      throw new R2UploadError(
        signRes.status === 403
          ? "You don't have permission to upload this file."
          : signRes.status === 413
            ? "That file is too large to upload."
            : signRes.status === 415
              ? "That file type isn't supported."
              : "Couldn't start the upload. Please try again.",
        detail
      );
    }
    signed = (await signRes.json()) as SignResponse;
  } catch (e) {
    if (e instanceof R2UploadError) throw e;
    throw new R2UploadError("Couldn't reach the upload service. Check your connection.", e);
  }

  // 2. Upload directly to R2. Headers must match what the Worker signed.
  try {
    const putRes = await fetch(signed.uploadUrl, {
      method: "PUT",
      headers: { "Content-Type": contentType, ...signed.headers },
      body: blob,
    });
    if (!putRes.ok) throw new Error(`R2 responded ${putRes.status}`);
  } catch (e) {
    throw new R2UploadError("Upload failed. Check your connection and try again.", e);
  }

  return `${PUBLIC_URL.replace(/\/+$/, "")}/${signed.key}`;
}

export async function uploadPropertyPhoto(
  propertyId: string,
  localUri: string,
  index: number
): Promise<string> {
  const compressed = await compressImageForUpload(localUri);
  return uploadUriTo("property-photo", propertyId, index, compressed, asJpeg);
}

export async function uploadMaintenancePhoto(
  maintenanceId: string,
  localUri: string,
  index: number
): Promise<string> {
  const compressed = await compressImageForUpload(localUri);
  return uploadUriTo("maintenance-photo", maintenanceId, index, compressed, asJpeg);
}

export async function uploadMaintenanceVideo(
  maintenanceId: string,
  localUri: string
): Promise<string> {
  // Videos are not compressed client-side (Expo has no built-in video
  // transcoder); we simply cap selectable duration in the picker UI instead.
  return uploadUriTo("maintenance-video", maintenanceId, 0, localUri, videoType);
}

export async function uploadProfilePhoto(userId: string, localUri: string): Promise<string> {
  const compressed = await compressImageForUpload(localUri);
  return uploadUriTo("profile-photo", userId, 0, compressed, asJpeg);
}
